accommodationRoot/accommodation/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                        # Examples:
                        # url(r'^$', 'accommodation.views.home', name='home'),
                        # url(r'^blog/', include('blog.urls')),

                        url(r'^hotels/', include('hotels.urls', namespace="hotels")),
                        url(r'^admin/', include(admin.site.urls)),
)

accommodationRoot/hotels/urls.py
from django.conf.urls import patterns, url

from hotels import views

urlpatterns = patterns('',
                        url(r'^$', views.index, name='index'),
                        url(r'^index.html$', views.index, name='index'),
                        url(r'^index/all/$', views.index_all_rooms, name='index_all_rooms'),
                        url(r'^three-room-list.html$', views.three_rooms_list, name='three_rooms_list'),
                        url(r'^two-columns-rooms-list.html$', views.two_columns_rooms_list,
                            name='two_columns_rooms_list'),
                        url(r'(?P<room_id>\d+)/room-with-one-bedroom.html$', views.room_with_one_bedroom,
                            name='room_with_one_bedroom'),
                        url(r'^choose-date-page/$', views.choose_date_page,
                            name='choose_date_page'),
                        url(r'(?P<room_id>\d+)/choose-room-page/$', views.choose_room_page,
                            name='choose_room_page'),
                        url(r'choose-room-page/$', views.choose_room_page,
                            name='choose_room_page'),
                        url(r'(?P<room_id>\d+)/checkout/$', views.checkout,
                            name='checkout'),
                        url(r'(?P<room_id>\d+)/payment/$', views.payment,
                            name='payment'),
                        url(r'(?P<room_id>\d+)/confirmation/', views.confirmation,
                            name='confirmation'),
                        )

accommodationRoot/hotels/models.py
from __future__ import unicode_literals
from django.utils import encoding
from django.db import models


# Create your models here.


class Hotel(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    hotel = models.ForeignKey(Hotel)
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=10, unique=True)
    description_short = models.CharField(max_length=200, default="room short description")
    description_long = models.CharField(max_length=1000, default="room long description")
    caption = models.CharField(max_length=200, default="room caption")
    type = models.CharField(max_length=200, default="room type")
    double_bed_size = models.CharField(max_length=200, default="Double")
    double_bed_num_of = models.IntegerField(default=1)
    single_bed_size = models.CharField(max_length=200, default="Single")
    single_bed_num_of = models.IntegerField(default=1)
    max_num_of_guests = models.IntegerField(default=2)
    base_rate = models.FloatField(default=100)
    num_of_guests_for_base_rate = models.IntegerField(default=2)
    num_of_guests_increment_for_extra_rate = models.IntegerField(default=2)
    extra_rate_for_guests_increment = models.FloatField(default=0.)
    extra_rate_percentage_for_guests_increment = models.FloatField(default=0.)

    def __str__(self):
        return self.name


class RoomImage(models.Model):
    room = models.ForeignKey(Room)
    path = models.CharField(max_length=500)
    purpose = models.CharField(max_length=50)
    resolution = models.CharField(max_length=100)
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.path


class ImageLayer(models.Model):
    room_image = models.ForeignKey(RoomImage)
    text = models.CharField(max_length=500)
    div_attributes = models.CharField(max_length=1000, default='')
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.div_attributes


class Country(models.Model):
    iso_code = models.CharField(max_length=20)
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Guest(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    email_address = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Address(models.Model):
    address = models.CharField(max_length=254)
    city = models.CharField(max_length=254)
    zipcode = models.CharField(max_length=20)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.address + ' ' + self.city + '\n' + self.zipcode + ', ' + str(self.country)


class AddressType(models.Model):
    type = models.CharField(max_length=30)


class GuestAddress(models.Model):
    unique_together = ['guest', 'address']
    guest = models.ForeignKey(Guest)
    address = models.ForeignKey(Address)
    address_type = models.ForeignKey(AddressType)


class Booking(models.Model):
    guest = models.ForeignKey(Guest)
    room = models.ForeignKey(Room)
    check_in_date = models.DateField(verbose_name="Check In")
    check_out_date = models.DateField(verbose_name="Check Out")
    date_created = models.DateField(verbose_name="Booking Date", auto_now_add=True)
    time_created = models.DateField(verbose_name="Booking Time", auto_now_add=True)

    def __str__(self):
        return "Check in: " + self.check_in_date.strftime('%d/%m/%Y') + " Check out: " + \
               self.check_out_date.strftime('%d/%m/%Y')


class Season(models.Model):
    name = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    room_season = models.ManyToManyField(Room, through='RoomSeason', through_fields=('season', 'room'))

    def __str__(self):
        return self.name


class RoomSeason(models.Model):
    season = models.ForeignKey(Season)
    room = models.ForeignKey(Room)
    rate = models.FloatField(default=100)

    class Meta:
        unique_together = ['room', 'season']

    def __str__(self):
        return "Season: " + str(self.season) + ' for Room:' + str(self.room)


class Setting(models.Model):
    date_format = models.CharField(max_length=12, default="european")
    currency_symbol = models.CharField(max_length=12, default=u"\u00A3")
    currency_code = models.CharField(max_length=12, default="GBP")

    def __str__(self):

        return "Date Format: " + self.date_format + "\nCurrency: "\
               + encoding.smart_str(self.currency_symbol.encode('unicode-escape'), encoding='ascii', errors='ignore')

accommodationRoot/hotels/views.py
from django.shortcuts import render
# from django.template import RequestContext, loader

# Create your views here.
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# from datetime import date, datetime, timedelta
from hotels.models import Hotel, Room, Guest, Setting, RoomImage, ImageLayer
from django.db.models import Q

import pickle

from datetime import datetime, timedelta, date
# import subprocess
import paypalrestsdk
# import json
from hotels.room_data import start_rate
from hotels.room_data import get_nights_rates_in_season_for_num_of_guests


def index_all_rooms(request):
    return index(request, 'yes')


def index(request, show_all_rooms='no'):
    room_image_layers_dict = {}
    if show_all_rooms == 'no':
        # show first 3 rooms
        rooms_list = Room.objects.order_by('name')[:2]
        booking_list = {}
        overview_image_dict = {}
        for room in rooms_list:
            booking_list[str(room.id)] = get_booking_list(room)
            overview_image_dict[str(room.id)] = get_overview_image_dict(room)
            room_images_set = RoomImage.objects.filter(room__pk=room.pk)

            for room_image in room_images_set:
                image_layer_set = ImageLayer.objects.filter(room_image__pk=room_image.pk)
                room_image_layers_dict[room_image] = image_layer_set

    else:
        # show all rooms
        rooms_list = Room.objects.order_by('name')
        booking_list = get_booking_list_all()
        overview_image_dict = get_overview_image_dict_all()
    print(booking_list)
    print(overview_image_dict)
    print(overview_image_dict.keys())

    context = {'rooms_list': rooms_list, 'booking_list': booking_list, 'overview_image_dict': overview_image_dict,
               'room_image_layers_dict': room_image_layers_dict}
    return render(request, 'hotels/index.html', context)


# def accommodation(request, hotel_id):
#     hotels_list = Hotel.objects.order_by('city')
#     try:
#         hotel = Hotel.objects.get(pk=hotel_id)
#     except Hotel.DoesNotExist:
#         raise Http404
#     # rooms_list = hotel.room_set.all()
#     context = {'hotels_list': hotels_list, 'hotel': hotel}
#
#     return render(request, 'hotels/accommodation.html', context)
#

def room_details(request, hotel_id, room_id):
    hotels_list = Hotel.objects.order_by('city')
    hotel = Hotel.objects.get(pk=hotel_id)
    try:
        room = Room.objects.get(pk=room_id)
    except Hotel.DoesNotExist:
        raise Http404
    context = {'hotels_list': hotels_list, 'hotel': hotel, 'room': room}
    return render(request, 'hotels/room-detail.html', context)


def three_rooms_list(request):
    rooms_list = Room.objects.order_by('name')

    context = {'rooms_list': rooms_list}
    return render(request, 'hotels/three-rooms-list.html', context)


def get_booking_list_all():
    rooms_list = Room.objects.order_by('name')
    booking_list = {}

    for room in rooms_list:
        booking_list[str(room.id)] = get_booking_list(room)
    return booking_list


def get_image_dict_all():
    rooms_list = Room.objects.order_by('name')
    image_dict = {}

    for room in rooms_list:
        image_dict[str(room.id)] = get_image_dict(room)
    return image_dict


def get_image_dict(room):
    image_dict_per_room = {}
    room_image_set = room.roomimage_set.filter(room_id=room.id)
    for roomImage in room_image_set:
        if roomImage.purpose in image_dict_per_room:
            pass
        else:
            image_dict_per_room[roomImage.purpose] = []

        image_dict_per_room[roomImage.purpose].append(roomImage)
        print image_dict_per_room
    return image_dict_per_room


def get_overview_image_dict(room):
    image_dict_per_room = get_image_dict(room)
    if 'OVERVIEW' in image_dict_per_room:
        print('hello')
        return image_dict_per_room['OVERVIEW']
    else:
        return []


def get_overview_image_dict_all():
    rooms_list = Room.objects.order_by('name')
    overview_image_dict = {}

    for room in rooms_list:
        overview_image_dict[str(room.id)] = get_overview_image_dict(room)
    return overview_image_dict


def get_booking_list(room):
        booking_list_per_room = {}

        booking_set = room.booking_set.filter(check_out_date__gte=date.today())
        # booking_set = room.booking_set.filter(room_id=room.id)
        for booking in booking_set:
            booking_list_per_room[booking.check_in_date.strftime('%Y-%m-%d')] = {'available': '0',
                                                                                   'info': 'check_in',
                                                                                   'promo': '',
                                                                                   'bind': 1,
                                                                                   'notes': '',
                                                                                   'status': 'booked',
                                                                                   'price': room.base_rate}
            booking_list_per_room[booking.check_out_date.strftime('%Y-%m-%d')] = {'available': '0',
                                                                                    'info': 'check_out',
                                                                                    'promo': '',
                                                                                    'bind': 3,
                                                                                    'notes': '',
                                                                                    'status': 'booked',
                                                                                    'price': room.base_rate + 10}
            number_of_nights = booking.check_out_date - booking.check_in_date
            in_date = booking.check_in_date
            for i in range(number_of_nights.days - 1):
                in_date += timedelta(days=1)
                booking_list_per_room[in_date.strftime('%Y-%m-%d')] = {'available': '0',
                                                                                        'info': '',
                                                                                        'promo': '',
                                                                                        'bind': 2, 'notes': '',
                                                                                        'status': 'booked',
                                                                                        'price': room.base_rate + 20}

            print(booking.check_in_date)
            print(booking.check_out_date)
        return booking_list_per_room


def two_columns_rooms_list(request):
    rooms_list = Room.objects.order_by('name')
    booking_list = get_booking_list_all()
    print(booking_list)
    context = {'rooms_list': rooms_list, 'booking_list': booking_list}
    return render(request, 'hotels/two-columns-rooms-list.html', context)


def room_with_one_bedroom(request, room_id):
    room = Room.objects.get(pk=room_id)
    print(room)
    booking_list = get_booking_list(room)
    context = {'room': room, 'booking_list': booking_list}
    return render(request, 'hotels/room-with-one-bedroom.html', context)


def choose_date_page(request):
    context = {}
    return render(request, 'hotels/reservation-page-choose-date.html', context)


def get_formatted_date(date, dateformat='european'):
    print "date " + date
    if '-' in date:
        fields = date.split('-')
    else:
        fields = date.split('/')
    print fields
    formatted_date = fields[2] + '-' + fields[1] + '-' + fields[0]
    if dateformat == 'european':
        # format is dd-mm-yy
        formatted_date = fields[2] + '-' + fields[1] + '-' + fields[0]
    elif dateformat == 'american':
        # format received is mm/dd/yy
        formatted_date = fields[2] + '-' + fields[0] + '-' + fields[1]
    return formatted_date


def get_booking_data(request):
    context = {}
    check_in = ""
    check_out = ""
    children = '0'
    adults = '0'
    total_price = '0'
    first_name = ''
    last_name = ''
    email = ''
    if 'check-in' in request.POST and request.POST['check-in']:
        check_in = request.POST['check-in']
    if 'check-out' in request.POST and request.POST['check-out']:
        check_out = request.POST['check-out']
    if 'adults' in request.POST and request.POST['adults']:
        adults = request.POST['adults']
    if 'children' in request.POST and request.POST['children']:
        children = request.POST['children']
    if 'first_name' in request.POST and request.POST['first_name']:
        first_name = request.POST['first_name']
    if 'last_name' in request.POST and request.POST['last_name']:
        last_name = request.POST['last_name']
    if 'total_price' in request.POST and request.POST['total_price']:
        total_price = request.POST['total_price']
    if 'email' in request.POST and request.POST['email']:
        email = request.POST['email']
    context['check_in'] = check_in
    context['check_out'] = check_out
    try:
        context['adults'] = int(adults)
    except ValueError:
        context['adults'] = 2
    try:
        context['children'] = int(children)
    except ValueError:
        context['children'] = 0
    context['first_name'] = first_name
    context['last_name'] = last_name
    context['email'] = email
    context['total_price'] = float(total_price)
    return context


def choose_room_page(request, room_id="-1"):
    print 'choose_room_page'

    print(" room_id " + room_id)
    context = get_booking_data(request)
    check_in = context['check_in']
    check_out = context['check_out']

    setting = get_setting()
    date_format = setting.date_format

    check_in_date = get_formatted_date(check_in, date_format)
    check_out_date = get_formatted_date(check_out, date_format)

accommodationRoot/hotels/templates/hotels/index.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% extends "hotels/base.html" %}
{% load staticfiles %}
{% load hotels_extras %}
<head>
	{% block title %}
	<title>Main Detail</title>
    {% endblock %}
</head>
<body>
    {% block content %}
        <div id="room-view-wrap" class="main-rooms-list">
            <div class="container">
                <div id="main-news-header">Check our comfortable rooms</div>
                <div id="main-news-subheader"><p>Hover your mouse on one of images below and then click on calendar icon to check room's availability or magnifier icon to learn more about this room or reserve it online</p></div>
                <div id="container two-item-list">
                {% for room in rooms_list %}
                {% include "hotels/room-wrap.html"%}
                {% endfor %}
                </div>
                <div id="show-rooms-main-wrap">
                    <div id="show-rooms-main"><a href="{% url  'hotels:index_all_rooms'  %}"><span class="icon-star"></span><span>View all rooms</span></a></div>
                    <div style="clear:both"></div>
                </div>
            </div>
        </div>

    {% endblock content %}

<!--{ block info }
{ endblock info }
{ block location_info_event }
{ endblock location_info_event } -->
{% block footer %}
  {{ block.super }}
{% endblock footer %}
{% block footer_script %}
    {{ block.super }}
{% endblock footer_script %}

</body>
</html>

accommodationRoot/hotels/templates/hotels/reservation-page-choose-date.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% extends "hotels/reservation-page-base.html" %}
{% load staticfiles %}
{% load hotels_extras %}
<head>
    {% block title %}
    {% endblock title %}
    {% block reservation_widget %}
    {% endblock reservation_widget %}
</head>
<body>
{% block rev_slider %}
{% endblock rev_slider %}
{% block page_header %}
<!-- BEGIN PAGE TITLE -->

<style>
</style>

<div id="top-content-divider">
    <div class="container">
        <div id="main-title-wrap"> Reservation Page</div>
    </div>
</div>

<!-- END PAGE TITLE -->

{% endblock page_header %}
{% block content %}

		<!-- BEGIN PAGE CONTENT -->
		<div class="container reservation-page-main-wrap">
{% block reservation_stages %}
    {{ block.super }}
    <script>
        (function($) {
            $(document).ready(function() {
                $("#reservation-breadcrumb-wrap").children().removeAttr('id');
                $("#reservation-breadcrumb-wrap").children('div:nth-child(1)').attr('id','active')

            })
        })(jQuery);
    </script>
{% endblock reservation_stages %}


{% block step_left %}
                <!-- BEGIN STEP 2 RESERVATION FORM -->
								<!-- BEGIN STEP 1 RESERVATION FORM -->
			<form method="POST" id="reservation-step1-form" action="{% url 'hotels:choose_room_page' %}">
                {% csrf_token %}
				<div class="five columns step1 alpha">
					<div id="reservation-info">
						<div id="reservation-info-header"><span class="icon-shopping-cart"></span>Your Booking</div>

                            <div id="reservation-info-content">
                                <div id="reservation-check-in">
                                    <div>Check-in</div>
                                    <input type="text" placeholder="check-in-date" id="check-in-date" name="check-in" class="reservation-form-field" readonly="true">
                                </div>
                                <div id="reservation-check-out">
                                    <div>Check-out</div>
                                    <input type="text" placeholder="check-out-date" id="check-out-date" name="check-out" class="reservation-form-field" readonly="true">
                                </div>
                                <div class="clear"></div>


                                <div id="room-guest1" >
								<div class="reservation-room-adults" name="adults-number">
                                    <div>Adults</div>						<select name="adults">
																				<option value="1">1</option>
																				<option value="2">2</option>
																				<option value="3">3</option>
																				<option value="4">4</option>
																				<option value="5">5</option>
																				<option value="6">6</option>
																				<option value="7">7</option>
																			</select>
								</div>
								<div class="reservation-room-children" name="children-number">
									<div>Children</div>						<select name="children">
																				<option value="0">0</option>
																				<option value="1">1</option>
																				<option value="2">2</option>
																				<option value="3">3</option>
																				<option value="4">4</option>
																				<option value="5">5</option>
																				<option value="6">6</option>
																				<option value="7">7</option>
																			</select>
								</div>
							</div>

                                <div class="clear"></div>
						</div>
					</div>
				</div>
				<div class="eleven columns reservation-content page-left-sidebar">
					<div id="reservation-data-selection"></div>
					<input type="hidden" value="" name="Date" id="Date" />
                    <input type="hidden" value=""  name="dateformat" id="dateformat" />
                    <script type='text/javascript'>
                        var inputDateFormat = document.getElementById("dateformat");
                        inputDateFormat.value = bookingOption.dateformat;
                    </script>
                    <button type="submit" id="reservation-step1-button">Check Availability</button>
				</div>

			</form>

			<!-- END STEP 1 RESERVATION FORM -->

{% endblock step_left %}

{% block step_right %}
{% endblock step_right %}
			<!-- END STEP 2 RESERVATION FORM -->



		</div>

<!-- END PAGE CONTENT -->


{% endblock content %}
{% block info %}
{% endblock info %}
{% block location_info_event %}
{% endblock location_info_event %}
{% block footer %}
  {{ block.super }}
{% endblock footer %}
</body>
</html>

accommodationRoot/hotels/templates/hotels/reservation-page-choose-room.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% extends "hotels/reservation-page-base.html" %}
{% load staticfiles %}
{% load hotels_extras %}
<head>
    {% block title %}
    {% endblock title %}
    {% block reservation_widget %}
    {% endblock reservation_widget %}
</head>
<body>
{% block rev_slider %}
{% endblock rev_slider %}
{% block page_header %}
<!-- BEGIN PAGE TITLE -->

<style>
</style>

<div id="top-content-divider">
    <div class="container">
        <div id="main-title-wrap"> Reservation Page</div>
    </div>
</div>

<!-- END PAGE TITLE -->

{% endblock page_header %}
{% block content %}

		<!-- BEGIN PAGE CONTENT -->
		<div class="container reservation-page-main-wrap">
{% block reservation_stages %}
    {{ block.super }}
    <script>
        (function($) {
            $(document).ready(function() {
                $("#reservation-breadcrumb-wrap").children().removeAttr('id');
                $("#reservation-breadcrumb-wrap").children('div:nth-child(2)').attr('id','active')

            })
        })(jQuery);
    </script>
{% endblock reservation_stages %}


{% block step_left %}
                <!-- BEGIN STEP 2 RESERVATION FORM -->
				<div class="five columns step2 alpha">
							<div id="reservation-info" class="step2-reservation-info">
								<div id="reservation-info-header"><span class="icon-shopping-cart"></span>Your Booking1</div>
								<div id="reservation-info-content">
									<div id="reservation-check-in">
										<div>Check-in</div>
										<div class="reservation-date-value">{{ check_in }}</div>
									</div>
									<div id="reservation-check-out">
										<div>Check-out</div>
										<div class="reservation-date-value">{{ check_out }}</div>
									</div>
									<div class="clear"></div>
									<div id="reservation-guests">
										<div>Guests</div>


										<div class="room-guests-wrap" id="room-guests-wrap1">
											Adults: <span class='adult'>{{ adults }}</span>, Children: <span class='children'>{{ children }}</span>
										</div>

									</div>
									<div id="edit-reservation">Edit Reservation</div>
								</div>
							</div>

							<form id="resend-step2" action="{% url 'hotels:choose_room_page' %}" method="POST">
                        {% csrf_token %}
						<div id="reservation-info">
							<div id="reservation-info-header"><span class="icon-shopping-cart"></span>Your Booking2</div>

							<div id="reservation-info-content">
								<div id="reservation-check-in">
									<div>Check-in</div>
									<input type="text" placeholder="check-in date" id="check-in-date" name="check-in" class="reservation-form-field" readonly="true">
 								</div>
								<div id="reservation-check-out">
									<div>Check-out</div>
									<input type="text" placeholder="check-out date" id="check-out-date" name="check-out" class="reservation-form-field" readonly="true">
								</div>
								<div class="clear"></div>

								<div id="reservation-room">

								</div>

                                <div id="room-guest" >
									<div class="reservation-room-adults" name="adults-number">
										<div>Adults</div>							<select name="adults">
																						<option value="1">1</option>
																						<option value="2">2</option>
																						<option value="3">3</option>
																						<option value="4">4</option>
																						<option value="5">5</option>
																						<option value="6">6</option>
																						<option value="7">7</option>
																						<option value="8">8</option>
																					</select>
									</div>
									<div class="reservation-room-children" name="children-number">
										<div>Children</div>							<select name="children">
																						<option value="0">0</option>
																						<option value="1">1</option>
																						<option value="2">2</option>
																						<option value="3">3</option>
																						<option value="4">4</option>
																						<option value="5">5</option>
																						<option value="6">6</option>
																						<option value="7">7</option>
																					</select>
									</div>
								</div>
                                <input type="hidden" value=""  name="dateformat" id="dateformat" />
                                <script type='text/javascript'>
                                    var inputDateFormat = document.getElementById("dateformat");
                                    inputDateFormat.value = bookingOption.dateformat;
                                </script>

                                <button id="resend-submit" type="submit">Apply Changes</button>
								<div id="cancel-resend-button">Cancel</div>
								<div class="clear"></div>
							</div>
						</div>
					</form>
				</div>
{% endblock step_left %}

{% block step_right %}
				<div class="eleven columns reservation-content page-left-sidebar step2">
					<h4>The room that you selected:</h4>
                    <div class='reservation-room-wrap'>
                    {% for room in available_rooms %}

                        {% with room.id|stringformat:"s" as room_id %}
                           {% with "hotels/content/uploads/2013/12/room"|add:room_id|add:'-375x249.jpg' as hrefPath %}
							<form class="room-reservation-wrap" action="{% url 'hotels:checkout' room_id %}" method="post">
                                {% csrf_token %}
                     			<img width="375" height="249" src="{% static hrefPath %}" class="reservation-list-image wp-post-image" alt="{{ room.description_short }}" />
                                <div class="room-reservation-title">{{ room.description_short }}</div>
								<input name="room-title" type="hidden" value="{{ room.description_short }}" />
								<input name="adults" type="hidden" value="{{ adults }}" />
								<input name="children" type="hidden" value="{{ children }}" />
                                {% with total_price_for_room|get_item:room.id as total_price_this_room %}
                                    <input name="total_price" type="hidden" value="{{ total_price_this_room }}" />
                                {% endwith %}								<!--<input name="room-id" type="hidden" value="{{ room_id }}">-->
								<div class="room-reservation-description">{{ room.description_long }}</div>
                                <input type="hidden" value=""  name="dateformat" id="dateformat" />
                                <script type='text/javascript'>
                                    var inputDateFormat = document.getElementById("dateformat");
                                    inputDateFormat.value = bookingOption.dateformat;
                                </script>
			                    <button type="submit" class="room-reservation-select">Select Room</button>
								<div class="room-reservation-price">

										<div>
									    	<span>from</span> &pound;{{ min_rate|get_item:room.id }}<span>/night</span>
                                    	</div>

                                    <div class="room-reservation-pricebreakdown"><span class="icon-info-sign"></span>view price breakdown</div>
                                    {% include "hotels/price-breakdown.html" %}
   							    </div>

                                <!--<input name="day-ids" type="hidden" value="3362,3363,3364,3365,3366,3367,3368,3369">-->
								<div class="clear"></div>
							</form>
                            {% endwith %}
                        {% endwith %}
                    {% endfor %}

						</div>
				</div>
{% endblock step_right %}
			<!-- END STEP 2 RESERVATION FORM -->



		</div>

<!-- END PAGE CONTENT -->


{% endblock content %}
{% block info %}
{% endblock info %}
{% block location_info_event %}
{% endblock location_info_event %}
{% block footer %}
  {{ block.super }}
{% endblock footer %}
</body>
</html>